[package]
name = "chibi_engine"
version = "0.1.0"
edition = "2021"
resolver="2"

[dependencies]
rand = { version = "0.8.5" }

[dependencies.vendor]
path="../vendor"
#features = ["generator"]

[lib]
path = "src/lib.rs"
