[package]
name = "testbed"
version = "0.1.0"
edition = "2021"
resolver="2"

[dependencies]
chibi_engine = { path="../../engine" }
common       = { path="../../common" }
assetlib     = { path="../../assetlib", features = ["importer"] } #temp.

[[bin]]
name = "testbed"
path = "src/main.rs"
